### ISSUE TITLE
Forms 0.2.0 api

### ISSUE THREAD

**Issue by ryanmenzer** [relevantmedia/alice_node#13]
- [x] use new forms api to finish survey model
- [x] remove empty answers from profile service
- [ ] progress tracker on the sidebar

**Comment by relevantmedia** [comment]
added form controls for check box group and changed profile answer value in ngStore to object if checkbox group. Need to get object value saved into database. Might be related to enumerated values.

**Comment by relevantmedia** [comment]
@pobras8 Are you going to add a progress tracker or is this issue closed?

**Comment by pobras8** [comment]
@relevantmedia it's on my todo list

**Comment by pobras8** [comment]
#75
