### ISSUE TITLE
handle error when navigating to profileView with no id

### ISSUE THREAD

**Issue by relevantmedia** [relevantmedia/alice_node#17]
error when id is not present or server does not respond. 
- [ ] redirect back to activeRoute with message?
- [ ] display message on profile page without id?

**Comment by relevantmedia** [comment]
- [ ] add exception checking for id is valid and id is in admin region
- [ ] add redirection in profileview is prarms and if profile

**Comment by pobras8** [comment]
Need to do region check, but may not be related to this anymore.
