### ISSUE TITLE
Change "complete" flag to "status" for Profile

### ISSUE THREAD

**Issue by pobras8** [relevantmedia/alice_node#24]
Status options:
-Assigned/Placed
-Coordinator (MTL comment complete, but awaiting Coordinator placement/assignment)
-MTL (survey complete, but awaiting MTL Comment)
-Started (started survey but not complete)(% complete? is this even necessary? *Ask Kent)
-NotStarted (not started survey at all)

Changes will need to be made in both the API and in node.

**Comment by relevantmedia** [comment]
Emoted completed from Api and added status. #41
