### ISSUE TITLE
survey load on refresh

### ISSUE THREAD

**Issue by relevantmedia** [relevantmedia/alice_node#38]
currentUser is null by default until User has been set from api. 

until users profiles have been pulled from db, answers is null and survey errors out

**Comment by relevantmedia** [comment]
answers in general.ts

**Comment by pobras8** [comment]
I'm still getting this bug when I refresh on the survey. 

EXCEPTION: Error in http://localhost:4200/app/survey/views/general.html:
TypeError: Cannot read property 'answers' of undefined
    at CombineLatestSubscriber.eval [as project] (profile.service.js:96)
