### ISSUE TITLE
profile status needs to be set/updated along each step of the process

### ISSUE THREAD

**Issue by pobras8** [relevantmedia/alice_node#62]
empty profile starts with status "not-started", once they answer a question it should be set to "started". Once they have submitted their completed form, it should update to "mtl". Once MTL's comment, it should change to "coordinator". Once assigned, it should update to "assigned".

Our seed data is also wrong for these cases. Right now we have statuses like "mtl", and "assigned", but they haven't completed the survey (or don't have all answers). This isn't a real-world scenario and could be an issue with testing soon.

#24 , #41

**Comment by relevantmedia** [comment]
- [ ] not-started and started and assigned need to be added to profile.filter

**Comment by pobras8** [comment]
Moving to own issue:
not-started and started and assigned need to be added to profile.filter

#85
