### ISSUE TITLE
Update profile cards

### ISSUE THREAD

**Issue by relevantmedia** [relevantmedia/alice_node#78]
- [ ] show all preferences, maybe in a scroll list so that card does not get too big.
- [ ] add link/button to send reminder to mtl if mtl comment has not been made. This would be an email that goes out but, we can add a method to profileCard and a link for now.
- [x] add button to finalize placement and notify staff member. Final step in process is (Finailized or Notified) have a designator on the profile card that staff have been notified.
- [x] be able to assign without an mtl comment. Assign should be able to happen anytime. Just have to make sure that status does not change after profile has been assigned, even if mtl makes a comment latter.

**Comment by pobras8** [comment]
Also adding in a notify button on the profile view

**Comment by pobras8** [comment]
Will move over similar logic/functionality implemented in profileView #84
