### ISSUE TITLE
Add Question to Survey

### ISSUE THREAD

**Issue by relevantmedia** [relevantmedia/alice_node#97]
Here's the question Craig would like added.  Craig Ryan said we are if we can make it happen this year we will for next.

Question: Are you considering stint or ICS for 2017-2018?  
Yes or No Option

If yes what's your level of interest?
Low, Moderate, High, Off the Charts High

**Comment by relevantmedia** [comment]
Also ... can add "Which are you considering?" Choose: "Staff Stint" ... or ... "ICS" ... or ... "not sure which one."

**Comment by pobras8** [comment]
Updated seed data with new questions and updated conditionals and projects list
